### ISSUE TITLE
Date Cell

### ISSUE THREAD

**Issue by daniftodi** [davidpelfree/sjxlsx#8]
When I try to getValue() from a date cell, the returned value is an integer.

How can I obtain the date value from a date cell ?

**Comment by FranzJr** [comment]
I use this to know if the date is fine also i can get the date value whit org.apache.poi.ss.usermodel.DateUtil Library from POI, DOC (https://poi.apache.org/apidocs/org/apache/poi/ss/usermodel/DateUtil.html)

if (cell.getCellType() == Cell.CELL_TYPE_NUMERIC) {
            if (DateUtil.isCellDateFormatted(cell)) {
                return true;
            }
}

If you just want to get the Date value you can get from the Integer you get http://stackoverflow.com/questions/10477714/converting-integer-time-stamp-into-java-date

**Comment by daniftodi** [comment]
Thank you for your response. Integer that I'm getting is not a time stamp, is something around 3000. I think is not related with the data that I have in excel cells.

I don't have in sjxlxs a method getCellType().

**Comment by FranzJr** [comment]
Yes because i mix poi advantages whit speed of sjxlxs but i share whit you how you get the value for the integer you get from sjxlxs native.
Also continue using org.apache.poi.ss.usermodel.DateUtil library.

String/Integer value = cell.getCellValue(columnNumber);
try {
            Date date = DateUtil.getJavaDate(Double.valueOf(value), TimeZone.getDefault());
            DateFormat dateFormat = DateFormat.getDateInstance();
            dateFormat.format(date).toString()
            return true;
        } catch (Exception e) {
            try {
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy/MM/dd (HH:mm:ss)", Locale.getDefault());
                simpleDateFormat.setLenient(false);
                simpleDateFormat.parse(value);
                return true;
            } catch (Exception ex) {
                try {
                    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd-MM-yyyy", Locale.getDefault());
                    simpleDateFormat.setLenient(false);
                    simpleDateFormat.parse(value);
                    return true;
                } catch (Exception ex1) {
                    try {
                        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd (HH:mm:ss)", Locale.getDefault());
                        simpleDateFormat.setLenient(false);
                        simpleDateFormat.parse(value);
                        return true;
                    } catch (Exception ex2) {
                        showError("It is not a date, " + columnNumber + " must to be a date");
                        return false;
                    }
                }
            }
        }

Please try and let me know if works for you.
